# Generated by Django 3.1.6 on 2021-03-24 10:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='licensePlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=50)),
                ('crime_case_count', models.IntegerField(default=0)),
                ('crime_alert', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Incedence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_light_no', models.CharField(blank=True, max_length=50)),
                ('vehicleType', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('offence', models.CharField(blank=True, max_length=50)),
                ('licensePlate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.licenseplate')),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mr.', max_length=5)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(default='male', max_length=20)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('licensePlate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ocr.licenseplate')),
            ],
        ),
    ]
