# Generated by Django 3.1.6 on 2021-03-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_auto_20210324_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drivers',
            new_name='Driver',
        ),
        migrations.AlterModelTable(
            name='driver',
            table='driver',
        ),
    ]
