# Generated by Django 3.1.6 on 2021-03-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_auto_20210324_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='licensePlate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.licenseplate'),
        ),
    ]
