# Generated by Django 3.1.6 on 2021-03-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_auto_20210324_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incedence',
            name='licensePlate',
            field=models.CharField(max_length=50),
        ),
    ]
