# Generated by Django 3.1.6 on 2021-03-24 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0007_auto_20210324_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='incedence',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
