# Generated by Django 3.1.6 on 2021-04-11 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0009_incedence_accuracy_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='incedence',
            name='Driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ocr.driver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='licensePlate',
            field=models.CharField(max_length=50),
        ),
    ]
