# Generated by Django 3.1.6 on 2021-04-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0011_auto_20210411_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidence',
            old_name='Driver',
            new_name='driver',
        ),
    ]
