# Generated by Django 3.1.6 on 2021-04-11 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0012_auto_20210411_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
