# Generated by Django 3.1.6 on 2021-04-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0013_auto_20210411_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidence',
            name='vehicleType',
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicleType',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
