# Generated by Django 3.1.6 on 2021-04-15 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0015_driver_driverid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='title',
        ),
    ]
