# Generated by Django 3.1.6 on 2021-04-15 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0016_auto_20210415_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseplate',
            name='car_number',
        ),
        migrations.RemoveField(
            model_name='licenseplate',
            name='crime_alert',
        ),
        migrations.RemoveField(
            model_name='licenseplate',
            name='date_created',
        ),
        migrations.AddField(
            model_name='incidence',
            name='offence_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licenseplate',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ocr.driver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licenseplate',
            name='crime_case_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
